### ISSUE TITLE
Conjuntos 

### ISSUE THREAD

**Issue by W1ll1am21** [SistemasTecTlaxiaco/actividad-4-mapa-mental-W1ll1am21#2]
[mapa mental william martinez.pdf](https://github.com/user-attachments/files/17176635/mapa.mental.william.martinez.pdf)

**Comment by LeinnaMora** [comment]
Manejo Conceptual y Dominio del Tema: 5/5
Relación entre los Conceptos Incluidos en el Mapa: 5/5
Calidad de la Presentación: 5/5
Jerarquía de temas: 5/5
CALIFICACIÓN FINAL: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
